title: My learning journey!
author: grandeen
email: notdankgreen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am about to start my lifelong dream of being a game developer! I'm going to make one using the source engine
  aaaandd I'm learning GitHub alongside it so I can collaborate with friends :))))

# social links
twitter_username: none lmao (n/a)
github_username:  grandeen

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
